#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/Mysql /var/log/Mysql

# copy config files

[[ ! -f /config/Mysql/config.json ]] && cp /app/Mysql/config.json /config/Mysql/config.json || echo "config.json exists"

exit 0